create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  phone text,
  address text,
  document_type text,
  document_number text,
  role text not null default 'usuario' check (role in ('usuario', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pqrs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  phone text,
  document_type text,
  document_number text,
  tipo text not null check (tipo in ('Petición', 'Queja', 'Reclamo')),
  mensaje text not null check (char_length(mensaje) between 10 and 2000),
  respuesta text check (respuesta is null or char_length(respuesta) <= 4000),
  estado text not null default 'Enviado' check (estado in ('Enviado', 'Respondido')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists role text;
alter table public.profiles alter column role set default 'usuario';
update public.profiles set role = 'usuario' where role is null or role not in ('usuario', 'admin');
alter table public.profiles alter column role set not null;
alter table public.profiles alter column phone drop not null;
alter table public.profiles alter column address drop not null;
alter table public.profiles alter column document_type drop not null;
alter table public.profiles alter column document_number drop not null;
alter table public.pqrs alter column phone drop not null;
alter table public.pqrs alter column document_type drop not null;
alter table public.pqrs alter column document_number drop not null;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (user_id, full_name, email, role)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', 'Usuario'), new.email, 'usuario')
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists crear_perfil_al_registrar on auth.users;
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.crear_perfil_usuario();
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql security definer stable set search_path = public as $$
  select exists (select 1 from public.profiles where user_id = (select auth.uid()) and role = 'admin');
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;
revoke all on table public.profiles, public.pqrs from anon, authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update on public.pqrs to authenticated;
alter table public.profiles enable row level security;
alter table public.pqrs enable row level security;

drop policy if exists "Users can view their own profile" on public.profiles;
drop policy if exists "Users can insert their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Profiles visible to owner or admins" on public.profiles for select to authenticated using ((select auth.uid()) = user_id or (select public.is_admin()));

drop policy if exists "Users can view their own pqrs" on public.pqrs;
drop policy if exists "Users can create pqrs" on public.pqrs;
drop policy if exists "Users can update their own pqrs" on public.pqrs;
drop policy if exists "Users can read permitted pqrs" on public.pqrs;
drop policy if exists "Users can create own pqrs" on public.pqrs;
drop policy if exists "Admins can respond to pqrs" on public.pqrs;
drop function if exists public.es_administrador();
create policy "Users can read permitted pqrs" on public.pqrs for select to authenticated using ((select auth.uid()) = user_id or (select public.is_admin()));
create policy "Users can create own pqrs" on public.pqrs for insert to authenticated with check ((select auth.uid()) = user_id and estado = 'Enviado' and respuesta is null);
create policy "Admins can respond to pqrs" on public.pqrs for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

create index if not exists pqrs_user_created_idx on public.pqrs (user_id, created_at desc);
create index if not exists pqrs_status_created_idx on public.pqrs (estado, created_at desc);

-- Promote administrators only from the SQL editor, after verifying the email.
-- update public.profiles set role = 'admin' where email = 'admin@centro-salud.gov.co';
